export const errorTests = [
  {
    name: 'empty-tag-in-various-places',
    description: 'Empty tags in various places (empty groups are allowed).',
    tests: [
      {
        name: 'end-in-comma',
        string: 'x,y,',
        issueCount: 1,
        hedCode: 'TAG_EMPTY',
        code: 'emptyTagFound',
        warning: false,
        explanation: 'Cannot end in a comma',
      },
      {
        name: 'double-in-comma',
        string: 'x,,y,',
        issueCount: 1,
        hedCode: 'TAG_EMPTY',
        code: 'emptyTagFound',
        warning: false,
        explanation: 'Cannot have double commas',
      },
      {
        name: 'leading-comma',
        string: ',x,y',
        issueCount: 1,
        hedCode: 'TAG_EMPTY',
        code: 'emptyTagFound',
        warning: false,
        explanation: 'Cannot have a leading comma',
      },
    ],
  },
  {
    name: 'extra-slash-in-various-places',
    description: 'Tags cannot have leading or trailing, or extra slashes',
    tests: [
      {
        name: 'leading-slash',
        string: '/x',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have a leading slash',
      },
      {
        name: 'double-slash',
        string: 'x//y',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have double slash',
      },
      {
        name: 'triple-slash',
        string: 'x///y',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have double slash',
      },
      {
        name: 'trailing-slash',
        string: 'x/y/',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have ending slash',
      },
      {
        name: 'value-slash',
        string: 'x /y',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have ending slash',
      },
    ],
  },
  {
    hedCode: 'SIDECAR_BRACES_INVALID',
    code: 'unopenedCurlyBrace',
    name: 'unopened-curly-brace',
    description: 'Tags cannot have leading or trailing, or extra slashes',
    tests: [
      {
        name: 'leading-close-brace',
        string: '}x',
        issueCount: 1,
        hedCode: 'SIDECAR_BRACES_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have a leading slash',
      },
      {
        name: 'double-slash',
        string: 'x//y',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have double slash',
      },
      {
        name: 'triple-slash',
        string: 'x///y',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have double slash',
      },
      {
        name: 'trailing-slash',
        string: 'x/y/',
        issueCount: 1,
        hedCode: 'TAG_INVALID',
        code: 'extraSlash',
        warning: false,
        explanation: 'Cannot have ending slash',
      },
    ],
  },
]
